# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import loader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redshift', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('s3_url', models.CharField(blank=True, max_length=400, null=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_file_name', models.CharField(blank=True, max_length=400, null=True)),
                ('bucket_name', models.CharField(max_length=200)),
                ('bundle_id', models.CharField(max_length=200)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=loader.models.LoaderStatus)),
                ('status_detail', models.TextField(blank=True, default='Ready', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoaderError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('loader_id', models.IntegerField()),
                ('bundle_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_record', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoaderSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('schema', models.CharField(default='redshift_etl', max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_header', models.BooleanField(default=True)),
                ('delimiter', models.CharField(default=',', max_length=200)),
                ('encoding', models.CharField(default='utf-8', max_length=200)),
                ('strategy', models.CharField(default='Replace', max_length=200, null=True)),
                ('sample_size', models.IntegerField(default=500)),
                ('skip_errors', models.IntegerField(default=500)),
                ('redshift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redshift.RedShiftDb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransformFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bundle_id', models.CharField(max_length=200)),
                ('meta_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loader',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.LoaderSetting'),
        ),
        migrations.AddField(
            model_name='loader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
