# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
