# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_loader_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
