# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0003_auto_20180411_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='loader_type',
            field=models.CharField(blank=True, default='file', max_length=200, null=True),
        ),
    ]
