# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_loader_loader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loader',
            name='file_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loader',
            name='s3_folder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
