# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_auto_20180611_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loader',
            old_name='s3_folder_name',
            new_name='s3_folder_key',
        ),
    ]
