# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_scraper_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='bucket_name',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
